Repository chanon-mike/naitei-journey, pull requests merged in 2023-08, with the labels that each got.

#10 Features/home UI
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/globals.css
  frontend/src/app/intern/page.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/page.tsx
  frontend/src/components/board/ActionBoard.tsx
  frontend/src/components/board/Board.tsx
  frontend/src/components/common/Header.tsx
  frontend/src/components/common/HeaderBox.tsx
  frontend/src/components/common/HeaderUserBox.tsx
  frontend/src/components/popup/CardDetail.tsx
  frontend/src/components/theme/ThemeRegistry.tsx
  frontend/src/components/theme/theme.ts
  frontend/tailwind.config.js
Labels: enhancement

#11 Bug/add location job
  README.md
  backend/README.md
  backend/app/db/migrations/versions/c1b647c9d210_add_card_position.py
  backend/app/models/job.py
  backend/app/repository/job.py
  backend/app/schemas/job.py
Labels: bug

#12 Features/board type
  README.md
  backend/app/db/migrations/versions/c1b647c9d210_add_card_position.py
  backend/app/main.py
  backend/app/repository/category.py
  backend/app/routers/category.py
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.js
  frontend/src/app/intern/data.tsx
  frontend/src/app/intern/page.tsx
  frontend/src/components/board/ActionArea.tsx
  frontend/src/components/board/ActionBoard.tsx
  frontend/src/components/board/Board.tsx
  frontend/src/types/board.ts
  frontend/src/utils/envValues.ts
Labels: bug, enhancement

#18 Features/fetch api
  README.md
  backend/app/db/migrations/versions/2a677768acf8_change_id_to_uuid4.py
  backend/app/db/migrations/versions/bc0627f3d016_relation_id_to_uuid4.py
  backend/app/models/application_status.py
  backend/app/models/category.py
  backend/app/models/job.py
  backend/app/models/selection_flow.py
  backend/app/repository/category.py
  backend/app/routers/category.py
  backend/app/schemas/application_status.py
  backend/app/schemas/category.py
  backend/app/schemas/job.py
  frontend/.eslintrc.js
  frontend/src/app/intern/data.tsx
  frontend/src/app/intern/page.tsx
  frontend/src/app/profile/page.tsx
  frontend/src/app/profile/user-button.tsx
  frontend/src/components/board/ActionArea.tsx
  frontend/src/components/board/ActionBoard.tsx
  frontend/src/components/board/Board.tsx
  frontend/src/components/popup/CardDetail.tsx
  frontend/src/components/popup/CardForm.tsx
  frontend/src/components/popup/DetailButton.tsx
  frontend/src/components/popup/FlowButton.tsx
  frontend/src/components/popup/FlowSelector.tsx
  frontend/src/components/popup/FlowSetting.tsx
  frontend/src/components/popup/PeriodSelector.tsx
  frontend/src/components/popup/ProcessButton.tsx
  frontend/src/components/popup/RankSelector.tsx
  frontend/src/components/popup/StateButton.tsx
  frontend/src/components/popup/StateSetting.tsx
  frontend/src/components/popup/StatusButton.tsx
  frontend/src/contexts/AccessTokenContext.tsx
  frontend/src/providers/AccessTokenProvider.tsx
  frontend/src/services/data.ts
  frontend/src/services/job.ts
  frontend/src/services/user.ts
  frontend/src/types/board.ts
  frontend/src/types/form.ts
Labels: bug, enhancement

#30 Features/edit delete frontend
  .vscode/settings.json
  frontend/src/app/intern/page.tsx
  frontend/src/components/board/ActionAreaCard.tsx
  frontend/src/components/board/ActionBoard.tsx
  frontend/src/components/board/AddButton.tsx
  frontend/src/components/board/Board.tsx
  frontend/src/components/common/ConfirmDialog.tsx
  frontend/src/components/popup/CardDetail.tsx
  frontend/src/components/popup/CardForm.tsx
  frontend/src/components/popup/PeriodSelector.tsx
  frontend/src/components/popup/RankingSelector.tsx
  frontend/src/components/popup/StatusSetting.tsx
  frontend/src/services/job.ts
  frontend/src/types/board.ts
Labels: enhancement

#34 Update requirements.txt
  backend/Makefile
  backend/app/schemas/job.py
  backend/poetry.lock
  backend/poetry.toml
  backend/pyproject.toml
  backend/requirements.txt
Labels: bug

#42 Features/realtime
  backend/app/main.py
  backend/app/routers/debug.py
  backend/poetry.lock
  backend/pyproject.toml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/intern/page.tsx
  frontend/src/atoms/authAtom.ts
  frontend/src/atoms/boardAtom.ts
  frontend/src/components/board/ActionBoard.tsx
  frontend/src/components/board/Board.tsx
  frontend/src/components/popup/CardDetail.tsx
  frontend/src/components/popup/CardForm.tsx
  frontend/src/contexts/AccessTokenContext.tsx
  frontend/src/libs/data.ts
  frontend/src/libs/envValues.ts
  frontend/src/libs/job.ts
  frontend/src/providers/AccessTokenProvider.tsx
Labels: bug, enhancement, priority: high

#41 Change CardDetail to CardDetailForm
  .vscode/settings.json
  frontend/src/components/board/ActionAreaCard.tsx
  frontend/src/components/common/CompanyDetailForm.tsx
  frontend/src/components/common/InternDetail.tsx
  frontend/src/components/common/UrlMemoForm.tsx
  frontend/src/components/popup/CardDetailForm.tsx
  frontend/src/components/popup/CardDetailLogic.tsx
  frontend/src/components/popup/CardForm.tsx
  frontend/src/components/popup/FlowSetting.tsx
  frontend/src/components/popup/PeriodSelector.tsx
  frontend/src/components/popup/RankingSelector.tsx
  frontend/src/components/popup/SplitDateAndPeriod.tsx
  frontend/src/components/popup/StatusSetting.tsx
Labels: enhancement, priority: high

#48 Update card position and category in realtime
  backend/app/repository/job.py
  backend/app/routers/job.py
  backend/app/schemas/job.py
  frontend/src/components/board/ActionBoard.tsx
  frontend/src/libs/job.ts
  frontend/src/types/board.ts
Labels: enhancement, priority: middle

#49 Add card to the end of column when create
  frontend/src/components/board/ActionBoard.tsx
  frontend/src/components/board/Board.tsx
  frontend/src/components/popup/CardForm.tsx
Labels: bug

#52 Add fulltime Page
  frontend/src/app/fulltime/page.tsx
  frontend/src/components/popup/CardDetailForm.tsx
  frontend/src/components/popup/CardForm.tsx
Labels: enhancement, priority: high

#57 Features/flow select
  backend/app/main.py
  backend/app/repository/selection_flow.py
  backend/app/routers/debug.py
  backend/app/routers/job.py
  frontend/src/components/board/ActionAreaCard.tsx
  frontend/src/components/board/ActionBoard.tsx
  frontend/src/components/board/Board.tsx
  frontend/src/components/common/ConfirmDialog.tsx
  frontend/src/components/popup/CardDetailForm.tsx
  frontend/src/components/popup/CardDetailLogic.tsx
  frontend/src/components/popup/CompanyDetailForm.tsx
  frontend/src/components/popup/FlowEditor.tsx
  frontend/src/components/popup/InternshipDetail.tsx
  frontend/src/components/popup/PeriodSelector.tsx
  frontend/src/components/popup/SplitDateAndPeriod.tsx
  frontend/src/components/popup/UrlMemoForm.tsx
  frontend/src/components/popup/applicationStatus/ProcessButton.tsx
  frontend/src/components/popup/applicationStatus/StatusButton.tsx
  frontend/src/components/popup/applicationStatus/StatusEditor.tsx
  frontend/src/components/popup/applicationStatus/StatusSetting.tsx
  frontend/src/components/popup/cardDetail/CardDetail.tsx
  frontend/src/components/popup/cardDetail/CardDetailForm.tsx
  frontend/src/components/popup/createCardForm/CardForm.tsx
  frontend/src/components/popup/selectionFlow/FlowEditSelector.tsx
  frontend/src/components/popup/selectionFlow/FlowEditor.tsx
  frontend/src/components/popup/selectionFlow/FlowSelector.tsx
  frontend/src/components/popup/selectionFlow/FlowSetting.tsx
  frontend/src/libs/job.ts
Labels: bug, enhancement, priority: high

#61 Features/google analysis
  .vscode/settings.json
  README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/layout.tsx
  frontend/src/components/common/GoogleAnalytics.tsx
  frontend/src/libs/envValues.ts
  frontend/src/libs/gtag.ts
Labels: enhancement

#62 Features/add loading
  frontend/src/app/profile/client-component.tsx
  frontend/src/app/profile/page.tsx
  frontend/src/app/profile/server-component.tsx
  frontend/src/components/board/ActionBoard.tsx
  frontend/src/components/popup/CompanyDetailForm.tsx
  frontend/src/components/popup/cardDetail/CardDetail.tsx
  frontend/src/components/popup/cardDetail/CardDetailForm.tsx
  frontend/src/components/popup/createCardForm/CardForm.tsx
  frontend/src/components/popup/selectionFlow/FlowEditor.tsx
  frontend/src/libs/dragAndDrop.ts
Labels: enhancement

#63 Features/footer
  frontend/src/app/layout.tsx
  frontend/src/components/board/ActionBoard.tsx
  frontend/src/components/common/Footer.tsx
  frontend/src/components/popup/cardDetail/CardDetailForm.tsx
  frontend/src/components/popup/createCardForm/CardForm.tsx
  frontend/src/components/popup/selectionFlow/FlowEditor.tsx
Labels: enhancement

#65 Features/add explanation
  .vscode/settings.json
  frontend/src/app/page.tsx
  frontend/src/components/home/Explanation.tsx
  frontend/src/components/home/MovieExplanation.tsx
Labels: enhancement

#66 docs: Update README.md
  README.md
Labels: documentation
